name: CI

on:
    push:
        branches: ['*']
    pull_request:
        branches: ['*']

jobs:
    ci:
        runs-on: ubuntu-latest

        env:
            SERVER_PORT: ${{ secrets.SERVER_PORT }}
            DATABASE_URL: postgresql://${{ secrets.DATABASE_URL }}
            ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
            ACCESS_TOKEN_EXPIRES_IN: ${{ secrets.ACCESS_TOKEN_EXPIRES_IN }}
            REFRESH_TOKEN_EXPIRES_IN: ${{ secrets.REFRESH_TOKEN_EXPIRES_IN }}
            REDIS_URL: ${{secrets.REDIS_URL}}

        steps:
            - uses: actions/checkout@v3

            - name: Install dependencies
              run: npm ci

            - name: Build
              run: npm run build

            - name: Lint
              run: npm run lint

            - name: Run tests
              run: npm test
